### ISSUE TITLE
npm安装后运行项目import报错

### ISSUE THREAD

**Issue by Pipcao** [rr13k/vue3-super-flow#2]
**vue: "^3.2.20"**-ts-vite-ant
![image](https://github.com/rr13k/vue3-super-flow/assets/78398783/ef6791ec-aa17-4dbf-b133-1b0f349b9d30)

**Comment by rr13k** [comment]
缺少类型标准，并不影响执行..可以配置ts-ignore

**Comment by Pipcao** [comment]
好的感谢
